### PR TITLE
Fix quitting

### PR DESCRIPTION
**Pull request by PetrusM**
Two fixes to make quitting smoother. Also useful for people like me that take inspiration from your code !

### CODE REVIEW

**Comment by Akemi** [comment]
`Fix another crash when quitting.` seems fine. the removed function is deprecated anyway.

`Lock drawing when quitting to prevent MPV crash.` i believe this one should be possible without a lock.
i would probably first first try to stop or uninit the displaylink on close, before the uninitMPV() call. we could also modify the canDraw call in the layer similar to here https://github.com/mpv-player/mpv/blob/master/video/out/mac/gl_layer.swift#L141-L150 which actually checks if there is a frame to render https://github.com/mpv-player/mpv/blob/0cea7b9ffbcf23c774a881f5d1d14f2fbbd86d5b/osdep/macos/libmpv_helper.swift#L107-L116 though this uses a lock too, so we might need a lock after all.

**Comment by PetrusM** [comment]
Another simple solution without lock would be
```swift
private var isQuitting = false
```
```swift
case MPV_EVENT_SHUTDOWN:
            isQuitting = true
            mpv_render_context_free(mpvRenderContext)
            mpvRenderContext = nil
            mpv_terminate_destroy(mpv)
            mpv = nil
            NSApp.terminate(self)
```
```swift
override func canDraw(inCGLContext ctx: CGLContextObj,
                          pixelFormat pf: CGLPixelFormatObj,
                          forLayerTime t: CFTimeInterval,
                          displayTime ts: UnsafePointer<CVTimeStamp>?) -> Bool {
        !isQuitting
    }
```
I don't know if this is better, but avoiding lock on display function seems a good idea...

I am now trying stopping displaylink first. 

Anyway, I have no crash without the `Lock drawing when quitting to prevent MPV crash.` commit with your example, only with my own project using mpv.

**Comment by PetrusM** [comment]
As for just doing this :
```swift
 case MPV_EVENT_SHUTDOWN:
                uninitDisplaylink()
                mpv_render_context_free(mpvRenderContext)
                mpvRenderContext = nil
                mpv_terminate_destroy(mpv)
                mpv = nil
```
It still leads to a `EXC_BAD_ACCESS (code=1, address=0x0)` crash on the `mpv_render_context_free` instruction :
Capture d’écran 2020-09-16 à 14 38 29

I even tried to do `uninitDisplaylink()` before sending the `quit` command to mpv, same result.

**Comment by Akemi** [comment]
did you forget to to return !isQuitting in the canDraw() function, or is it just a copy/paste error?

i guess, since the actual draw call can happen at an arbitrary time (async call on a separate queue), we do need a lock to properly shutdown.

**Comment by PetrusM** [comment]
Well, in the last swift version (but I can't tell when it started), `return` is optional when there is a single statement in the function (or in `get` for properties).

I realize it does still crash even with the lock, but less often. I might miss some code that should be locked...

**Comment by Akemi** [comment]
on a side note, imo doing something like this implicitly is kinda horrible. i wonder who though that was a good idea.

then i would only like to merge the other commit, for now. would be nice if you could adjust the PR for now, or change it later if you find the actual reason.

**Comment by PetrusM** [comment]
Done.

I am still investigating for the other crash. FYI I found the "lock" solution thanks to [iina project implementation](https://github.com/iina/iina/blob/b5c4383d151dcf84067761b8ded1bba0fe82de81/iina/ViewLayer.swift#L108).

**Comment by Akemi** [comment]
i wouldn't look too much into the iina implementation. it's rather convoluted, doesn't use the newest API additions and you might copy some of their presentations bugs. the cocoa-cb/libmpv backend/implementation is up to date and has a somewhat nice libmpv abstraction (libmpv bindings) that one might be able to use with some slight changes.

would you mind squashing those 3 commits?

**Comment by PetrusM** [comment]
Done squashing.

I am not really sure of what you mean by "cocoa-cb/libmpv backend/implementation".
Does it mean I should take a look at functions located under mpv/osdep/macos in the mpv repository ?

**Comment by Akemi** [comment]
thanks for your work.

yeah in that folder too.
this is a libmpv abstraction, at least some parts of it. it also uses a deinit lock https://github.com/mpv-player/mpv/blob/master/osdep/macos/libmpv_helper.swift
the layer itself https://github.com/mpv-player/mpv/blob/master/video/out/mac/gl_layer.swift
here for some of the usage libmpv. https://github.com/mpv-player/mpv/blob/master/video/out/cocoa_cb_common.swift

**Comment by PetrusM** [comment]
Thank you very much for your help. I will take a close look at this.

**Pull request merged**
